"""update document  table

Revision ID: 9c40c8b4fa62
Revises: 50c9ebfc892d
Create Date: 2024-04-24 15:31:35.241338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c40c8b4fa62'
down_revision = '50c9ebfc892d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('documents', sa.Column('copies', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('is_electronic_copy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_electronic_copy')
    op.drop_column('documents', 'copies')
    # ### end Alembic commands ###
