"""create credit card table

Revision ID: c58f697138c0
Revises: 0372a187caa6
Create Date: 2024-04-26 20:38:32.314603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58f697138c0'
down_revision = '0372a187caa6'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('creditcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardnumber', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('payment_address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='creditcard_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creditcards')
    # ### end Alembic commands ###
